### ISSUE TITLE
[BUG] Bot hangs after a certain amount of time

### ISSUE THREAD

**Issue by dysphoniq** [SpoticordMusic/Spoticord#12]
**Describe the bug**
Cannot get Spoticord to join voice channel

**To Reproduce**
1. Set up Spoticord Music bot as instructions direct
2. use `/join` to attempt to have Spoticord join current channel
3. See that Bot does not respond with error "The application did not respond"

**Expected behavior**
The bot should join channel and allow music to be played.  Notably, it does check for channel permission before not responding.

**Screenshots**
Removed channel permissions and the bot successfully checked & reported on that. After updating permissions, get the same error as before.
![image](https://user-images.githubusercontent.com/22550932/206061679-f0401ad9-ab84-4e62-b5bd-f5d2e29f6e07.png)

**Additional context**
Spoticord Version
Current version: 2.0.0-beta

Was working roughly two weeks ago, not sure when it stopped.  Not sure how to get a more robust error message, let me know if there's anything I can do to help diagnose the issue!

**Comment by DaXcess** [comment]
This is a known issue, there is a resource leak somewhere in the code which I haven't been able to identify yet, which eventually causes the bot to hang. This is still something that is being looked in to.

**Comment by DaXcess** [comment]
This looks to be resolved in the last commit, I'm closing this for now.
