### ISSUE TITLE
[BUG] Hardcoded url in join voice error embed

### ISSUE THREAD

**Issue by spectrapulse** [SpoticordMusic/Spoticord#24]
**Describe the bug**
Self-Hosted Spoticord shows the wrong account linking URL when running into an error while joining the voice channel with no accounts linked.

**To Reproduce**
1. Unlink your Spotify and/or Discord account from self-hosted Spoticord.
2. Ask the bot to join your current voice channel.

**Expected behavior**
Bot would say where to link user's account with the correct URL.

**Screenshots**
![Image showing the incorrect link in embed](https://cdn.kanker.dev/share/2023/09/25/1695666536.png)

**Additional context**
The instances in the source where this happens with this specific issue are here:
https://github.com/SpoticordMusic/spoticord/blob/4d12d381861728446c11cea793ecb5368228c4a1/src/bot/commands/music/join.rs#L244
https://github.com/SpoticordMusic/spoticord/blob/4d12d381861728446c11cea793ecb5368228c4a1/src/bot/commands/music/join.rs#L258
I would fix it myself and make a pr except I don't have experience with Rust so it's very possible that I would come up with an undesirable solution :p

**Comment by DaXcess** [comment]
Patch is ready on the `dev` branch, will keep issue open until it's merged into `main` on the next version
