### ISSUE TITLE
[ENHANCEMENT] /playing command auto-update

### ISSUE THREAD

**Issue by DaXcess** [SpoticordMusic/Spoticord#26]
Currently you need to issue the /playing command every time when a song has been changed.
A desirable feature would be to make it so that the last /playing command that was issued this session will automatically be updated when the song changes.

Will have to look into which events all should cause an update, e.g. only when a new song starts playing, or also when the player gets paused/resumed/seeked.

**Comment by Bloodiko** [comment]
Or alternatively instead of updating the last /playing command, the bot could send the /playing info automatically to the last channel it got used in, since the chat may be scrolling by with new messages, leaving the updated /playing behind where its not seen anymore.
