### ISSUE TITLE
[ENHANCEMENT] Volume Control

### ISSUE THREAD

**Issue by ilikpoptarts** [SpoticordMusic/Spoticord#32]
**Is your feature request related to a problem? Please describe.**
Music is excessively loud until each user lowers volume on the bot manually. Less educated users and mobile users struggle to understand discord volume controls and bots.

**Describe the solution you'd like**
A volume command, or some way to set the default volume to a percentage for the server.

**Comment by DaXcess** [comment]
This feature already exists

![image](https://github.com/SpoticordMusic/spoticord/assets/46288749/5b584bd3-1f53-4493-8026-6c81cbf8bfce)
