### ISSUE TITLE
Audio hangs [BUG]

### ISSUE THREAD

**Issue by RG007JM** [SpoticordMusic/Spoticord#34]
**Something**
The audio hangs for about 1 second before resuming (about every 15 seconds), the music never stops playing (looking at the Spotify Player)

**To Reproduce**
Type /join
Try to listen to music

**Expected behavior**
No audio hangs

**Screenshots**
Ain't got any

**Comment by DaXcess** [comment]
This is a networking issue which is out of my hands unfortunately. Discord RTP servers keep dropping packets for some reason, but probably not Discord's fault, but hosting's fault.

A good workaround that almost always works is swapping the region for the voice channel to force Spoticord to use a different RTP server.
