### ISSUE TITLE
[BUG] Error in user data setup: environment variable not found

### ISSUE THREAD

**Issue by nennneko5787** [SpoticordMusic/Spoticord#38]
**Describe the bug**
After building the bot from source code and setting environment variables, I get an `Error in user data setup: environment variable not found`, presense is not updated and commands are not responding

**To Reproduce**
1. Build the bot using the `cargo build --release` command
2. Place the .env file and set environment variables as per README
3. run the `./target/release/spoticord` command 

**Expected behavior**
Error log
```
ubuntu@ip-172-31-32-225:~/spoticord$ ./target/release/spoticord
[2024-09-18T13:55:39Z INFO spoticord]Today is a good day!
[2024-09-18T13:55:39Z INFO spoticord]- Spoticord
[2024-09-18T13:55:42Z INFO spoticord::bot]Successfully logged in as SpotiPlayer
Error in user data setup: environment variable not found
```
**Screenshots**
![image](https://github.com/user-attachments/assets/d0551329-16b0-4b54-acb4-c2cbbafafb74)

**Additional context**
This occurs with or without `sudo`

**Comment by ZorgordianInZilo** [comment]
Also getting this:

![{66679050-F65F-405A-8095-D4C525769C44}](https://github.com/user-attachments/assets/e4d5e82d-e699-42f3-9285-ef74e40ad48f)

**Comment by ZorgordianInZilo** [comment]
I added a Redis Cache server to my stack and that issue went away after assigning it to KV_URL environment variable.

**Comment by DaXcess** [comment]
The `kv` feature is enabled by default, which requires you to supply a `KV_URL` for stats collection. For simple self hosting, this feature isn't needed, and can be disabled by using `--no-default-features` during build/run.

**Comment by DaXcess** [comment]
![image](https://github.com/user-attachments/assets/55165815-3e13-44da-9a69-b91e005f91e1)

Added more concise logging for this missing env var in 58df939280244ca4c6cfb3997571ade785f80cd8. 
I'll be closing this issue now.
